"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os
import dj_database_url

load_dotenv()  # reads .env file automatically

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = os.environ.get('SECRET_KEY')
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

STRIPE_SECRET_KEY      = os.environ.get('STRIPE_SECRET_KEY', '')
STRIPE_PUBLISHABLE_KEY = os.environ.get('STRIPE_PUBLISHABLE_KEY', '')
STRIPE_WEBHOOK_SECRET  = os.environ.get('STRIPE_WEBHOOK_SECRET', '')

PAYPAL_CLIENT_ID = os.environ.get('PAYPAL_CLIENT_ID', '')
PAYPAL_SECRET    = os.environ.get('PAYPAL_SECRET', '')
PAYPAL_MODE      = os.environ.get('PAYPAL_MODE', 'sandbox')

FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:5173')

# ── ALLOWED_HOSTS ──────────────────────────────────────────────────────────────
# Comma-separated list in the env var, e.g.:
#   ALLOWED_HOSTS=edupath-backend.onrender.com,127.0.0.1,localhost
_raw_hosts = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1')
ALLOWED_HOSTS = [h.strip() for h in _raw_hosts.split(',') if h.strip()]

# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cloudinary',

    # Third-party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'django_filters',
    'django_elasticsearch_dsl',
    'channels',
    'whitenoise',

    # Custom apps
    'users',
    'courses',
    'payments',
    'chat',
    'notifications',
    'progress',
    'certificates',
    'announcements',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # serve static files on Render
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

CERT_FONTS_DIR = BASE_DIR / "static" / "fonts"

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database — PostgreSQL on Supabase
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# Preferred:  set DATABASE_URL in .env  (copy the connection string from
#             Supabase → Project Settings → Database → Connection string).
# Fallback:   set individual DB_NAME / DB_USER / DB_PASSWORD / DB_HOST / DB_PORT.
#
# Supabase connection-pooler (pgbouncer) — recommended for serverless or
# high-concurrency workloads — runs on port 6543.  Set USE_PGBOUNCER=true
# in .env to switch to the pooler endpoint automatically.

_USE_PGBOUNCER = os.environ.get('USE_PGBOUNCER', 'false').lower() == 'true'
_DEFAULT_PORT = '6543' if _USE_PGBOUNCER else '5432'

_DATABASE_URL = os.environ.get('DATABASE_URL', '').strip()
_PARSED_DB = None

# When running in Docker, the local Postgres container does not use SSL.
# Set DOCKER_ENV=true in docker-compose to skip SSL for local dev.
_DOCKER_ENV = os.environ.get('DOCKER_ENV', 'false').lower() == 'true'
_SSL_REQUIRE = not _DOCKER_ENV

if _DATABASE_URL:
    try:
        _PARSED_DB = dj_database_url.parse(
            _DATABASE_URL,
            conn_max_age=int(os.environ.get('CONN_MAX_AGE', 600)),
            ssl_require=_SSL_REQUIRE,
        )
        # Remove sslmode from OPTIONS when running local Docker DB
        if _DOCKER_ENV and _PARSED_DB.get('OPTIONS'):
            _PARSED_DB['OPTIONS'].pop('sslmode', None)
    except Exception:
        # Placeholder / malformed URL — fall through to individual env vars
        _PARSED_DB = None

if _PARSED_DB:
    DATABASES = {'default': _PARSED_DB}
else:
    _db_options = {} if _DOCKER_ENV else {'sslmode': 'require'}
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME':     os.environ.get('DB_NAME', 'postgres'),
            'USER':     os.environ.get('DB_USER', 'postgres'),
            'PASSWORD': os.environ.get('DB_PASSWORD', ''),
            'HOST':     os.environ.get('DB_HOST', 'localhost'),
            'PORT':     os.environ.get('DB_PORT', _DEFAULT_PORT),
            'CONN_MAX_AGE': int(os.environ.get('CONN_MAX_AGE', 600)),
            'OPTIONS': _db_options,
        }
    }

# When using pgbouncer in transaction-pooling mode, server-side cursors and
# prepared statements must be disabled — Django's DISABLE_SERVER_SIDE_CURSORS
# handles the ORM side.
if _USE_PGBOUNCER:
    DATABASES['default']['DISABLE_SERVER_SIDE_CURSORS'] = True


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# ── Static files ───────────────────────────────────────────────────────────────
# WhiteNoise serves compressed, cache-busted static files directly from Daphne
# without needing a separate CDN step. STATICFILES_STORAGE controls the manifest.

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# ── Media files / Cloudinary ──────────────────────────────────────────────────
USE_CLOUDINARY = os.environ.get('USE_CLOUDINARY', 'false').lower() == 'true'

if USE_CLOUDINARY:
    CLOUDINARY_STORAGE = {
        'CLOUD_NAME': os.environ.get('CLOUDINARY_CLOUD_NAME', ''),
        'API_KEY': os.environ.get('CLOUDINARY_API_KEY', ''),
        'API_SECRET': os.environ.get('CLOUDINARY_API_SECRET', ''),
    }

MEDIA_URL = '/media/'
if not USE_CLOUDINARY:
    MEDIA_ROOT = BASE_DIR / 'media'

STORAGES = {
    'default': {
        'BACKEND': 'cloudinary_storage.storage.MediaCloudinaryStorage' if USE_CLOUDINARY else 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

WHITENOISE_MANIFEST_STRICT = True

# Custom Auth Model
AUTH_USER_MODEL = 'users.User'

# REST Framework Config
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

# SimpleJWT Config
from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': False,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}

# WebSockets Channels Config
ASGI_APPLICATION = 'core.asgi.application'

# ── Redis ─────────────────────────────────────────────────────────────────────
# REDIS_URL drives both the cache backend and the Channel Layer broker so there
# is a single place to change for prod (set REDIS_URL in your .env or platform
# environment variables to point at Upstash / Redis Cloud / Railway Redis etc.).
# DB index 1 is used for the cache; channels_redis defaults to DB 0 internally
# via its own key-space management, so the two subsystems never collide.
REDIS_URL = os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379/1')

# Django cache backend — django-redis wraps redis-py with Django's cache API.
# KEY_PREFIX namespaces every key so this instance can safely share a Redis
# server with other apps without key collisions.
# TIMEOUT of 300 s is the global default; individual cache.set() calls in
# dashboard_service.py and admin_reports_views.py override it per use-case.
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': REDIS_URL,
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        },
        'KEY_PREFIX': 'edupath',
        'TIMEOUT': 300,  # seconds — default for keys that don't set their own TTL
    }
}

# Channel Layers — Redis broker so Django Channels WebSocket messages are
# routed correctly across all Daphne workers (InMemoryChannelLayer only works
# for a single process and silently drops cross-process messages).
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [
                {
                    'address': REDIS_URL,
                    'socket_timeout': None,
                }
            ],
        },
    },
}

# ── CORS ───────────────────────────────────────────────────────────────────────
# CORS_ALLOWED_ORIGINS: comma-separated list of allowed origins.
# Minimum required:  your Vercel frontend URL.
# Example:  CORS_ALLOWED_ORIGINS=https://edupath.vercel.app,http://localhost:5173
_raw_cors = os.environ.get('CORS_ALLOWED_ORIGINS', FRONTEND_URL)
CORS_ALLOWED_ORIGINS = [o.strip() for o in _raw_cors.split(',') if o.strip()]
CORS_ALLOW_CREDENTIALS = True

# ── CSRF ───────────────────────────────────────────────────────────────────────
# Required when cookies are used cross-domain (SameSite=None) so Django will
# accept POST/PUT/DELETE requests coming from your Vercel frontend.
# Example: CSRF_TRUSTED_ORIGINS=https://edupath.vercel.app,https://edupath-backend.onrender.com
_raw_csrf = os.environ.get('CSRF_TRUSTED_ORIGINS', FRONTEND_URL)
CSRF_TRUSTED_ORIGINS = [o.strip() for o in _raw_csrf.split(',') if o.strip()]

# Authentication Backends
AUTHENTICATION_BACKENDS = [
    'users.backends.EmailAuthBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# Stripe Configurations
STRIPE_PUBLIC_KEY = os.environ.get('STRIPE_PUBLIC_KEY', 'pk_test_mock')
STRIPE_SECRET_KEY = os.environ.get('STRIPE_SECRET_KEY', 'sk_test_mock')
STRIPE_WEBHOOK_SECRET = os.environ.get('STRIPE_WEBHOOK_SECRET', 'whsec_mock')

# PayPal Configurations
PAYPAL_CLIENT_ID = os.environ.get('PAYPAL_CLIENT_ID', 'paypal_mock')
PAYPAL_SECRET = os.environ.get('PAYPAL_SECRET', 'paypal_mock')
PAYPAL_MODE = os.environ.get('PAYPAL_MODE', 'sandbox')  # sandbox or live

# Frontend URL for redirects
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:5173')

# Email Configuration
BREVO_API_KEY = os.environ.get('BREVO_API_KEY', '')
if os.environ.get('EMAIL_HOST'):
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.environ.get('EMAIL_HOST')
    EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
    EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() in ('true', '1', 't')
    EMAIL_USE_SSL = os.environ.get('EMAIL_USE_SSL', 'False').lower() in ('true', '1', 't')
    EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
    EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')
    EMAIL_TIMEOUT = int(os.environ.get('EMAIL_TIMEOUT', 10))
    DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'no-reply@edupath.com')
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    DEFAULT_FROM_EMAIL = 'no-reply@edupath.com'

# ── Auth Cookie ────────────────────────────────────────────────────────────────
# When the frontend (Vercel) and backend (Render) are on different domains,
# SameSite must be 'None' so the browser sends the HttpOnly refresh cookie
# cross-site. SameSite=None requires Secure=True (HTTPS), which is always
# the case on both Vercel and Render. For local dev (DEBUG=True) keep 'Lax'
# so you don't need HTTPS on localhost.
AUTH_COOKIE_NAME = 'refresh_token'
AUTH_COOKIE_SECURE = not DEBUG           # True in production (HTTPS only)
AUTH_COOKIE_SAMESITE = 'Lax' if DEBUG else 'None'  # 'None' required for cross-domain
AUTH_COOKIE_PATH = '/api/auth/'          # cookie only sent to auth endpoints

# ── Elasticsearch ─────────────────────────────────────────────────────────────
# Toggle ES on/off — set ES_ENABLED=true in .env when you have an ES instance.
# When disabled the search endpoints still work but fall back to ORM queries so
# the app is fully functional even without a running Elasticsearch cluster.
ES_ENABLED = os.environ.get('ES_ENABLED', 'true').lower() == 'true'

_ES_HOST = os.environ.get('ES_HOST', 'localhost')
_ES_PORT = os.environ.get('ES_PORT', '9200')
_ES_SCHEME = os.environ.get('ES_SCHEME', 'http')
_ES_URL = f"{_ES_SCHEME}://{_ES_HOST}:{_ES_PORT}"

_es_conn = {
    'hosts': _ES_URL,
    'request_timeout': float(os.environ.get('ES_TIMEOUT', '2.0')),
}

# Optional auth — supports API key (Elastic Cloud) or basic auth (self-hosted)
_ES_API_KEY = os.environ.get('ES_API_KEY', '')
_ES_USER = os.environ.get('ES_USER', '')
_ES_PASSWORD = os.environ.get('ES_PASSWORD', '')

if _ES_API_KEY:
    _es_conn['api_key'] = _ES_API_KEY
elif _ES_USER and _ES_PASSWORD:
    _es_conn['http_auth'] = (_ES_USER, _ES_PASSWORD)

ELASTICSEARCH_DSL = {
    'default': _es_conn,
}

# Disable auto-sync signals when ES is not available so post_save / post_delete
# don't raise ConnectionError on every model save.
ELASTICSEARCH_DSL_AUTOSYNC = ES_ENABLED
ELASTICSEARCH_DSL_SIGNAL_PROCESSOR = 'django_elasticsearch_dsl.signals.RealTimeSignalProcessor'

# ── Logging ───────────────────────────────────────────────────────────────────
# Render captures stdout/stderr. Using a single StreamHandler to stdout gives
# Render's log-drain clean, timestamped, levelled lines for each request and
# exception — much easier to search than Django's default stderr-only output.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {name} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': os.environ.get('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
        # App-level loggers — set to DEBUG in dev via LOG_LEVEL env var
        'users': {
            'handlers': ['console'],
            'level': os.environ.get('LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
        'courses': {
            'handlers': ['console'],
            'level': os.environ.get('LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
        'payments': {
            'handlers': ['console'],
            'level': os.environ.get('LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
        'notifications': {
            'handlers': ['console'],
            'level': os.environ.get('LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
        'announcements': {
            'handlers': ['console'],
            'level': os.environ.get('LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
        'chat': {
            'handlers': ['console'],
            'level': os.environ.get('LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
    },
}
