# Generated by Django 6.0.6 on 2026-06-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('ENROLLMENT', 'Enrollment Event'), ('LESSON_ADDED', 'New Lesson Added'), ('QNA_REPLY', 'Q&A Reply'), ('REFUND', 'Refund Event'), ('ANNOUNCEMENT', 'Mentor Announcement')], default='ANNOUNCEMENT', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
