# Generated by Django 6.0.6 on 2026-06-29 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_alter_notification_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_object_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('ENROLLMENT', 'Enrollment'), ('COURSE_APPROVED', 'Course Approved'), ('COURSE_REJECTED', 'Course Rejected'), ('MENTOR_APPROVED', 'Mentor Approved'), ('NEW_QUESTION', 'New Question'), ('QUESTION_REPLY', 'Question Reply'), ('NEW_REVIEW', 'New Review'), ('PAYMENT_SUCCESS', 'Payment Successful'), ('REFUND_PROCESSED', 'Refund Processed'), ('CERTIFICATE_GENERATED', 'Certificate Generated'), ('LESSON_ADDED', 'New Lesson Added'), ('COURSE_UPDATED', 'Course Updated'), ('SYSTEM', 'System'), ('REFUND', 'Refund Event'), ('ANNOUNCEMENT', 'Mentor Announcement')], default='SYSTEM', max_length=30),
        ),
    ]
