# Generated by Django 6.0.6 on 2026-07-15 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0012_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('ENROLLMENT', 'Enrollment'), ('COURSE_APPROVED', 'Course Approved'), ('COURSE_REJECTED', 'Course Rejected'), ('MENTOR_APPROVED', 'Mentor Approved'), ('COURSE_PENDING_APPROVAL', 'Course Pending Approval'), ('NEW_QUESTION', 'New Question'), ('QUESTION_REPLY', 'Question Reply'), ('NEW_REVIEW', 'New Review'), ('PAYMENT_SUCCESS', 'Payment Successful'), ('REFUND_PROCESSED', 'Refund Processed'), ('CERTIFICATE_GENERATED', 'Certificate Generated'), ('LESSON_ADDED', 'New Lesson Added'), ('COURSE_UPDATED', 'Course Updated'), ('SYSTEM', 'System'), ('REFUND', 'Refund Event'), ('ANNOUNCEMENT', 'Mentor Announcement'), ('NEW_ANNOUNCEMENT', 'New Announcement'), ('REVIEW_REPORTED', 'Review Reported')], default='SYSTEM', max_length=30),
        ),
    ]
