# Generated by Django 6.0.6 on 2026-06-28 09:25 (hand-edited for data migration)

from django.db import migrations, models
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    Course = apps.get_model('courses', 'Course')
    seen = set()
    for course in Course.objects.all().order_by('id'):
        base = slugify(course.title) or f'course-{course.id}'
        slug = base
        counter = 1
        while slug in seen:
            slug = f'{base}-{counter}'
            counter += 1
        seen.add(slug)
        course.slug = slug
        course.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_course_id_alter_lesson_id_alter_module_id_and_more'),
    ]

    operations = [
        # 1. Add rating_average field
        migrations.AddField(
            model_name='course',
            name='rating_average',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        # 2. Add slug as nullable, non-unique first so existing rows can be populated
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(max_length=220, blank=True, null=True),
        ),
        # 3. Populate slugs for existing rows
        migrations.RunPython(populate_slugs, migrations.RunPython.noop),
        # Remove any leftover index from a previously interrupted run.
        migrations.RunSQL(
            sql=(
                'DROP INDEX IF EXISTS courses_course_slug_9c670f14_like; '
                'DROP INDEX IF EXISTS courses_course_slug_9c670f14;'
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
        # 4. Now enforce unique + remove null without triggering Django's
        # PostgreSQL slug index creation twice.
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER TABLE "courses_course" ALTER COLUMN "slug" SET NOT NULL;',
                    reverse_sql='ALTER TABLE "courses_course" ALTER COLUMN "slug" DROP NOT NULL;',
                ),
                migrations.RunSQL(
                    sql=(
                        'DO $$ BEGIN '
                        'ALTER TABLE "courses_course" '
                        'ADD CONSTRAINT "courses_course_slug_9c670f14_uniq" UNIQUE ("slug"); '
                        'EXCEPTION WHEN duplicate_object THEN NULL; '
                        'END $$;'
                    ),
                    reverse_sql='ALTER TABLE "courses_course" DROP CONSTRAINT IF EXISTS "courses_course_slug_9c670f14_uniq";',
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='course',
                    name='slug',
                    field=models.SlugField(max_length=220, blank=True, unique=True),
                ),
            ],
        ),
    ]
