# Generated by Django 6.0.6 on 2026-06-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_add_slug_to_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='total_reviews',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
