# Generated by Django 6.0.6 on 2026-07-04 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_total_reviews_review_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='is_submitted_for_review',
            field=models.BooleanField(default=False),
        ),
    ]
