# Generated by Django 6.0.6 on 2026-07-05 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_course_is_rejected_course_is_submitted_for_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(default='Development', max_length=100),
        ),
    ]
