# Generated by Django 6.0.6 on 2026-07-06 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_lessonprogress_completed_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseprogress',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='courseprogress',
            name='course',
        ),
        migrations.RemoveField(
            model_name='courseprogress',
            name='student',
        ),
        migrations.AlterUniqueTogether(
            name='lessonprogress',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='lessonprogress',
            name='course',
        ),
        migrations.RemoveField(
            model_name='lessonprogress',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='lessonprogress',
            name='student',
        ),
        migrations.DeleteModel(
            name='Certificate',
        ),
        migrations.DeleteModel(
            name='CourseProgress',
        ),
        migrations.DeleteModel(
            name='LessonProgress',
        ),
    ]
