# Generated by Django 6.0.6 on 2026-07-12 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_alter_courseprogress_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
