# Generated by Django 6.0.6 on 2026-07-11 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='areas_of_expertise',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='areas_of_interest',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='education_level',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='years_of_experience',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_complete',
            field=models.BooleanField(default=False),
        ),
    ]
