# Generated by Django 6.0.6 on 2026-07-16 14:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profile_areas_of_expertise_profile_areas_of_interest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, numbers and . or _ only.', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Enter a valid username. This value may contain only letters, numbers, and . or _ characters.', regex='^[a-zA-Z0-9._]+\\Z')], verbose_name='username'),
        ),
    ]
