# Generated by Django 6.0.6 on 2026-07-16 21:44

import certificates.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, storage=certificates.models.get_certificate_storage, upload_to='certificates/'),
        ),
    ]
